---
- name: Get Contour Manifest
  get_url:
      dest: /tmp/contour.yml 
      url: "{{ingress_manifest}}"

- name: Update Contour namespace
  replace:
      path: /tmp/contour.yml 
      regexp: '^(\s*)(name[space]*)?(:\s*)(projectcontour)\s*$'
      replace: '\1\2\3{{ingress_namespace}}'

- name: Deploy Contour
  community.kubernetes.k8s:
    definition: "{{ lookup('file', '/tmp/contour.yml') }}"
    state: present
    wait: yes
    wait_sleep: 5
    wait_timeout: 180
  register: contour_deploy
  changed_when: False

# - debug: msg="{{contour_deploy}}"


   