---
###################################
# Pre-req
###################################
- name: 'Check Pre-req'
  include_tasks: pre_reqs.yml
###################################
# Create
###################################
- name: 'Create KinD {{cluster_name}} Cluster'
  include_tasks: create.yml
  when: kind_create

###################################
# Destroy
###################################
- name: 'Destroy KinD {{cluster_name}} Cluster'
  include_tasks: create.yml
  when: kind_destroy
