---
###################################
# Pre-req
###################################
- name: 'Check KinD Pre-req'
  include_tasks: kind_pre_reqs.yml
  when: kind_create

###################################
# Create
###################################
- name: 'Create KinD {{ cluster_name }} Cluster'
  include_tasks: kind_create.yml
  when: kind_create

###################################
# Destroy
###################################
- name: 'Destroy KinD {{ cluster_name }} Cluster'
  include_tasks: kind_destroy.yml
  when: kind_destroy
