---
- name: Converge
  hosts: localhost
  connection: local

  collections:
  - community.kubernetes

  vars:
   ansible_python_interpreter: '{{ ansible_playbook_python }}'
   cluster_name: molecule-knative
   kind_home_dir: "/tmp/kind_test"
   deploy_knative: True

  roles:
    - role: kameshsampath.kind
