---
- name: Verify
  hosts: localhost
  connection: local

  collections:
    - community.kubernetes
    
  vars:
   ansible_python_interpreter: '{{ ansible_playbook_python }}'
   cluster_name: molecule-ingress
   kind_home_dir: /tmp/kind_test
   kind_version: v0.8.1
   kind_create: True
   deploy_ingress: True
   kind_cluster_config: "kind-cluster-config.yml"
   ingress_namespace: "contour-system"

  tasks:
   - import_tasks: ../common/tasks/verify.yml
   - import_tasks: ../common/tasks/ingress_verify.yml

- name: Destroy test resources
  import_playbook: destroy.yml