---
- name: prepare test env
  import_playbook: prepare.yml

- name: Converge
  hosts: all
  become: true

  collections:
    - community.kubernetes

  vars:
    ansible_python_interpreter: '/usr/bin/python3'
    deploy_ingress: False
    kind_create: False

  roles:
    - role: kameshsampath.kind
