---
- name: Destroy 'pre-req' test scenario environment
  hosts: localhost
  connection: local

  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    instance: molecule-kind-prereqs

  tasks:
    - name: "Destroy Test Environment {{ preq_docker_container_name }}"
      docker_container:
        name: '{{ instance }}'
        force_kill: True
        state: absent
