---
driver:
  name: delegated
  options:
    managed: False
    login_cmd_template: 'docker exec -ti {{ instance }} bash'
    ansible_connection_options:
      ansible_connection: docker
lint: |
  set -e
  yamllint .
# TODO #1 need fix  - not working OOTB  ansible-lint
platforms:
  - name: molecule-kind-prereqs
provisioner:
  name: ansible
  scenario:
    test_sequence:
      - lint
      - syntax
      - converge
      - idempotence
      - verify
verifier:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}   
  
