---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/common/requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
# TODO #1 need fix  - not working OOTB  ansible-lint
platforms:
  - name: molecule-kind
    dockerfile: molecule/commons/Dockerfile.j2
    image: quay.io/kameshsampath/ansible-kubernetes-centos8
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pull: False
    privileged: True
provisioner:
  name: ansible
verifier:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
