---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: molecule-kind
    image: geerlingguy/docker-centos8-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
  vars:
    cluster_name: molecule
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
