---
- name: Verify
  hosts: localhost
  connection: local

  collections:
    - community.kubernetes

  vars:
   ansible_python_interpreter: '{{ ansible_playbook_python }}'
   cluster_name: molecule
   kind_home_dir: "/tmp/kind_test"
   kind_version: v0.8.1
   ingress: False
   kind_cluster_config: "kind-cluster-config.yml"

  tasks:

  - import_tasks: ../common/tasks/verify.yml

- name: Destroy test resources
  import_playbook: destroy.yml