---
- name: kind-with-knative
  hosts: localhost
  connection: local

  collections:
    - community.kubernetes

  vars:
    # to ensure we are on python3
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    cluster_name: my-demo-cluster
    # Default versions are v0.16.0, you can overide it using knative_serving_version, knative_eventing_version
    deploy_knative: True

  roles:
    - role: kameshsampath.kind
