---
- name: kind-with-ingress
  hosts: localhost
  connection: local

  collections:
    - community.kubernetes

  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    cluster_name: my-demo-cluster

  roles:
    - role: kameshsampath.kind
