---
- name: Create
  hosts: localhost
  connection: local
  tasks:

   - name: Build vagrant molecule vm
     command:
       argv:
          - vagrant
          - up
     register: vup

   - fail: 
      msg: Unable to start vm
     when: vup.rc != 0

- name: Converge
  hosts: molecule-vm

  collections:
    - community.kubernetes

  vars:
   cluster_name: molecule
   deploy_knative: True
  
  roles:
    - role: kameshsampath.kind

- name: Destroy
  hosts: localhost
  connection: local
  tasks:

   - name: Destroy vagrant molecule vm
     command:
       argv:
          - vagrant
          - destroy
          - --force
     register: vdown

   - fail: 
      msg: Unable to destroy vm
     when: vdown is defined and vdown.rc != 0