# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 
  config.vm.box = "kameshsampath/ansible-centos8"
  config.vm.box_version = "0.1.0"

  config.vm.provider "virtualbox" do |vb|
     vb.cpus = 6
     vb.memory = "8192"
  end
 
  config.vm.provision "ansible_local" do |ansible|
    # since ansible is installed in basebox, skip install
    ansible.install = false
    ansible.playbook = "vm.yml"
    ansible.galaxy_command = "ansible-galaxy collection install community.kubernetes"
  end 

end
