---
- name: Verify
  hosts: molecule-vm

  collections:
  - community.kubernetes
    
  vars:
   
   cluster_name: molecule-knative
   kind_home_dir: /tmp/kind_test
   kind_version: v0.8.1
   kind_create: True
   deploy_ingress: True
   deploy_knative: True
   kind_cluster_config: "kind-cluster-config.yml"
   knative_version: v0.16.0
   knative_eventing_version: v0.16.0
   knative_serving_version: v0.16.0
   ingress_namespace: contour-system

  tasks:

   - import_tasks: ../common/tasks/verify.yml
   - import_tasks: ../common/tasks/ingress_verify.yml
  
   - name: Create Test namespace
     community.kubernetes.k8s:
      definition:      
        kind: Namespace
        metadata:
          name: molecule-knative-test
      state: present

   - import_tasks: ../deploy_knative/serving_verify.yml
   - import_tasks: ../deploy_knative/eventing_verify.yml