---
- name: Converge
  hosts: localhost
  connection: local

  collections:
    - community.kubernetes

  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    kind_home_dir: "/tmp/kind_test"
    deploy_ingress: False
    kind_create: False

  roles:
    - role: kameshsampath.kind
