---
- name: Verify
  hosts: localhost
  connection: local

  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    kind_create: False
    kind_destroy: False
    kind_version: v0.8.1
    kind_home_dir: "/tmp/kind_test"
    
  tasks:
  - name: Check if KinD is installed
    stat:
      path: "/usr/local/bin/kind"
    register: kind_dir_result
  
  # - debug: msg="{{kind_dir_result}}"

  - name: Verify KinD home directory exists
    assert:
      that: "{{ kind_dir_result.stat.exists and kind_dir_result.stat.executable }}"
  - name: Get KinD Version
    command:
      argv:
        - "{{kind_dir_result.stat.path}}"
        - version
    register: kind_version_out
  - name: Verify KinD version
    assert:
      that: "{{ kind_version_out.stdout is regex('^kind ' + kind_version + '.*')}}"
