---
- name: Verify
  hosts: localhost
  connection: local

  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    kind_create: False
    kind_destroy: False
    kind_version: v0.8.1
    kind_home_dir: "/tmp/kind_test"

  tasks:
   - import_tasks: ../common/tasks/verify.yml
