kind: Deployment
metadata:
  name: myapp
  namespace: molecule-ingress-test
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: quay.io/kameshsampath/quarkus-helloworld
          ports:
            - containerPort: 8080
