apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: myapp
  namespace: molecule-ingress-test
  labels:
    app: myapp
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: myapp
              servicePort: 80
